;
; File generated by cc65 v 2.17 - Git 535088fe
;
	.fopt		compiler,"cc65 v 2.17 - Git 535088fe"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_memcpy
	.import		_memset
	.export		_Config
	.export		_load_config
	.export		_save_config
	.export		_restore_default_config

.segment	"BSS"

_Config:
	.res	2,$00

; ---------------------------------------------------------------
; void __near__ load_config (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_load_config: near

.segment	"CODE"

	lda     #<(_Config)
	ldx     #>(_Config)
	jsr     pushax
	ldx     #$60
	lda     #$00
	jsr     pushax
	tax
	lda     #$02
	jmp     _memcpy

.endproc

; ---------------------------------------------------------------
; void __near__ save_config (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_save_config: near

.segment	"CODE"

	ldx     #$60
	lda     #$00
	jsr     pushax
	lda     #<(_Config)
	ldx     #>(_Config)
	jsr     pushax
	ldx     #$00
	lda     #$02
	jmp     _memcpy

.endproc

; ---------------------------------------------------------------
; void __near__ restore_default_config (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_restore_default_config: near

.segment	"CODE"

	ldx     #$60
	lda     #$00
	stz     ptr1
	stx     ptr1+1
	ldy     #$01
L0014:	sta     (ptr1),y
	dey
	bpl     L0014
	jmp     _save_config

.endproc

