;
; File generated by cc65 v 2.17 - Git 535088f
;
	.fopt		compiler,"cc65 v 2.17 - Git 535088f"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_geiger_pulses
	.export		_geiger_init
	.export		_cpm
	.export		_cpm2sievert

.segment	"BSS"

_geiger_pulses:
	.res	120,$00

; ---------------------------------------------------------------
; void __near__ geiger_init (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_geiger_init: near

.segment	"CODE"

	jsr     decsp1
	lda     #$00
	tay
L0023:	sta     (sp),y
	cmp     #$3C
	bcs     L0004
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L0020
	inx
	clc
L0020:	adc     #<(_geiger_pulses)
	sta     ptr1
	txa
	adc     #>(_geiger_pulses)
	sta     ptr1+1
	tya
	sta     (ptr1),y
	iny
	sta     (ptr1),y
	dey
	lda     (sp),y
	clc
	adc     #$01
	jmp     L0023
L0004:	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ cpm (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_cpm: near

.segment	"CODE"

	jsr     push0
	jsr     decsp1
	ldy     #$00
L0028:	sta     (sp),y
	cmp     #$3C
	bcs     L0011
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L0025
	inx
	clc
L0025:	adc     #<(_geiger_pulses)
	tay
	txa
	adc     #>(_geiger_pulses)
	tax
	tya
	jsr     ldaxi
	ldy     #$01
	jsr     addeqysp
	ldy     #$00
	lda     (sp),y
	clc
	adc     #$01
	jmp     L0028
L0011:	ldy     #$02
	jsr     ldaxysp
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; unsigned long __near__ cpm2sievert (unsigned int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_cpm2sievert: near

.segment	"CODE"

	jsr     pushax
	jsr     pushw0sp
	lda     #$39
	jsr     tosumula0
	jsr     axulong
	jmp     incsp2

.endproc

