;
; File generated by cc65 v 2.17 - Git 535088fe
;
	.fopt		compiler,"cc65 v 2.17 - Git 535088fe"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_hd44780_init
	.export		_hd44780_putc
	.export		_hd44780_write
	.export		_hd44780_puts
	.export		_hd44780_cmd
	.export		_hd44780_gotoxy
	.export		_hd44780_clrscr
	.import		_delay_16us
	.import		_delay_ms

.segment	"RODATA"

L006B:
	.byte	$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20
	.byte	$20,$20,$20,$20,$00
L0072	:=	L006B+0
L0079	:=	L006B+0
L0064	:=	L006B+0

; ---------------------------------------------------------------
; void __near__ hd44780_init (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_hd44780_init: near

.segment	"CODE"

	lda     #$64
	jsr     _delay_ms
	lda     #$30
	sta     $6380
	lda     #$64
	jsr     _delay_ms
	lda     #$30
	sta     $6380
	lda     #$07
	jsr     _delay_16us
	lda     #$30
	sta     $6380
	lda     #$07
	jsr     _delay_16us
	lda     #$38
	jsr     _hd44780_cmd
	lda     #$08
	jsr     _hd44780_cmd
	lda     #$01
	jsr     _hd44780_cmd
	lda     #$06
	jsr     _hd44780_cmd
	lda     #$0C
	jmp     _hd44780_cmd

.endproc

; ---------------------------------------------------------------
; void __near__ hd44780_putc (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_hd44780_putc: near

.segment	"CODE"

	jsr     pusha
L007C:	lda     $6380
	and     #$80
	bne     L007C
	lda     (sp)
	sta     $6381
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ hd44780_write (__near__ unsigned char *, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_hd44780_write: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp1
	lda     #$00
L007F:	sta     (sp)
	ldy     #$01
	cmp     (sp),y
	bcs     L0028
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (sp)
	tay
	lda     (ptr1),y
	jsr     _hd44780_putc
	lda     (sp)
	ina
	bra     L007F
L0028:	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ hd44780_puts (__near__ const unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_hd44780_puts: near

.segment	"CODE"

	jsr     pushax
	bra     L0035
L0033:	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	jsr     _hd44780_putc
	jsr     ldax0sp
	ina
	bne     L003A
	inx
L003A:	jsr     stax0sp
L0035:	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	bne     L0033
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ hd44780_cmd (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_hd44780_cmd: near

.segment	"CODE"

	jsr     pusha
L0080:	lda     $6380
	and     #$80
	bne     L0080
	lda     (sp)
	sta     $6380
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ hd44780_gotoxy (unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_hd44780_gotoxy: near

.segment	"CODE"

	jsr     pusha
	lda     #$00
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	bne     L0083
	lda     #$80
	bra     L0088
L0083:	lda     (sp),y
	cmp     #$01
	bne     L0085
	lda     #$C0
	bra     L0088
L0085:	lda     (sp),y
	cmp     #$02
	bne     L0087
	lda     #$94
	bra     L0088
L0087:	lda     (sp),y
	cmp     #$03
	bne     L0055
	lda     #$D4
L0088:	sta     (sp)
L0055:	dey
	lda     (sp),y
	cmp     #$14
	bcs     L0059
	clc
	adc     (sp)
	sta     (sp)
L0059:	lda     (sp)
	jsr     _hd44780_cmd
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ hd44780_clrscr (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_hd44780_clrscr: near

.segment	"CODE"

	lda     #$00
	jsr     pusha
	jsr     _hd44780_gotoxy
	lda     #<(L0064)
	ldx     #>(L0064)
	jsr     pushax
	lda     #$14
	jsr     _hd44780_write
	lda     #$01
	jsr     pusha
	dea
	jsr     _hd44780_gotoxy
	lda     #<(L006B)
	ldx     #>(L006B)
	jsr     pushax
	lda     #$14
	jsr     _hd44780_write
	lda     #$02
	jsr     pusha
	lda     #$00
	jsr     _hd44780_gotoxy
	lda     #<(L0072)
	ldx     #>(L0072)
	jsr     pushax
	lda     #$14
	jsr     _hd44780_write
	lda     #$03
	jsr     pusha
	lda     #$00
	jsr     _hd44780_gotoxy
	lda     #<(L0079)
	ldx     #>(L0079)
	jsr     pushax
	lda     #$14
	jmp     _hd44780_write

.endproc

