;
; File generated by cc65 v 2.17 - Git 535088fe
;
	.fopt		compiler,"cc65 v 2.17 - Git 535088fe"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_mktime
	.export		_m6242_init
	.export		_m6242_read_time_str
	.export		_m6242_read_date_str
	.export		_m6242_read_time_raw
	.export		_m6242_read_date_raw
	.export		_m6242_read_tm
	.export		_m6242_read_timestamp
	.export		_m6242_settime
	.export		_m6242_setdate
	.import		_delay_16us
	.export		_m6242_buf
	.export		_current_time
	.export		_timestamp

.segment	"BSS"

_m6242_buf:
	.res	10,$00
_current_time:
	.res	18,$00
_timestamp:
	.res	4,$00

; ---------------------------------------------------------------
; void __near__ m6242_init (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_m6242_init: near

.segment	"CODE"

	lda     #$04
	sta     $640D
	lda     #$06
	sta     $640E
	lda     #$01
	sta     $640F
	lda     #$04
	sta     $640F
	rts

.endproc

; ---------------------------------------------------------------
; __near__ unsigned char * __near__ m6242_read_time_str (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_m6242_read_time_str: near

.segment	"CODE"

	lda     #$05
	sta     $640D
	lda     $6405
	ldx     #$00
	and     #$03
	ldy     #$30
	jsr     incaxy
	sta     _m6242_buf
	lda     $6404
	ldx     #$00
	and     #$0F
	ldy     #$30
	jsr     incaxy
	sta     _m6242_buf+1
	lda     #$3A
	sta     _m6242_buf+2
	lda     $6403
	ldx     #$00
	and     #$0F
	ldy     #$30
	jsr     incaxy
	sta     _m6242_buf+3
	lda     $6402
	ldx     #$00
	and     #$0F
	ldy     #$30
	jsr     incaxy
	sta     _m6242_buf+4
	lda     #$3A
	sta     _m6242_buf+5
	lda     $6401
	ldx     #$00
	and     #$0F
	ldy     #$30
	jsr     incaxy
	sta     _m6242_buf+6
	lda     $6400
	ldx     #$00
	and     #$0F
	ldy     #$30
	jsr     incaxy
	sta     _m6242_buf+7
	stz     _m6242_buf+8
	lda     #$04
	sta     $640D
	lda     #<(_m6242_buf)
	ldx     #>(_m6242_buf)
	rts

.endproc

; ---------------------------------------------------------------
; __near__ unsigned char * __near__ m6242_read_date_str (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_m6242_read_date_str: near

.segment	"CODE"

	lda     #$05
	sta     $640D
	lda     $6407
	ldx     #$00
	and     #$0F
	ldy     #$30
	jsr     incaxy
	sta     _m6242_buf
	lda     $6406
	ldx     #$00
	and     #$0F
	ldy     #$30
	jsr     incaxy
	sta     _m6242_buf+1
	lda     #$2D
	sta     _m6242_buf+2
	lda     $6409
	ldx     #$00
	and     #$0F
	ldy     #$30
	jsr     incaxy
	sta     _m6242_buf+3
	lda     $6408
	ldx     #$00
	and     #$0F
	ldy     #$30
	jsr     incaxy
	sta     _m6242_buf+4
	lda     #$2D
	sta     _m6242_buf+5
	lda     $640B
	ldx     #$00
	and     #$0F
	ldy     #$30
	jsr     incaxy
	sta     _m6242_buf+6
	lda     $640A
	ldx     #$00
	and     #$0F
	ldy     #$30
	jsr     incaxy
	sta     _m6242_buf+7
	stz     _m6242_buf+8
	lda     #$04
	sta     $640D
	lda     #<(_m6242_buf)
	ldx     #>(_m6242_buf)
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ m6242_read_time_raw (__near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_m6242_read_time_raw: near

.segment	"CODE"

	jsr     pushax
	lda     #$05
	sta     $640D
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     $6405
	and     #$03
	sta     (ptr1)
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     $6404
	and     #$0F
	ldy     #$01
	sta     (ptr1),y
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     $6403
	and     #$0F
	ldy     #$02
	sta     (ptr1),y
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     $6402
	and     #$0F
	ldy     #$03
	sta     (ptr1),y
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     $6401
	and     #$0F
	ldy     #$04
	sta     (ptr1),y
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     $6400
	and     #$0F
	ldy     #$05
	sta     (ptr1),y
	lda     #$04
	sta     $640D
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ m6242_read_date_raw (__near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_m6242_read_date_raw: near

.segment	"CODE"

	jsr     pushax
	lda     #$05
	sta     $640D
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     $6407
	and     #$03
	sta     (ptr1)
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     $6406
	and     #$0F
	ldy     #$01
	sta     (ptr1),y
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     $6409
	and     #$0F
	ldy     #$02
	sta     (ptr1),y
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     $6408
	and     #$0F
	ldy     #$03
	sta     (ptr1),y
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     $640B
	and     #$0F
	ldy     #$04
	sta     (ptr1),y
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     $640A
	and     #$0F
	ldy     #$05
	sta     (ptr1),y
	lda     #$04
	sta     $640D
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ m6242_read_tm (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_m6242_read_tm: near

.segment	"CODE"

	lda     #$05
	sta     $640D
	lda     $6401
	ldx     #$00
	and     #$0F
	jsr     mulax10
	sta     ptr1
	stx     ptr1+1
	lda     $6400
	and     #$0F
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L019E
	inx
L019E:	sta     _current_time
	stx     _current_time+1
	lda     $6403
	ldx     #$00
	and     #$0F
	jsr     mulax10
	sta     ptr1
	stx     ptr1+1
	lda     $6402
	and     #$0F
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L019F
	inx
L019F:	sta     _current_time+2
	stx     _current_time+2+1
	lda     $6405
	ldx     #$00
	and     #$03
	jsr     mulax10
	sta     ptr1
	stx     ptr1+1
	lda     $6404
	and     #$0F
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L01A0
	inx
L01A0:	sta     _current_time+4
	stx     _current_time+4+1
	lda     $6407
	ldx     #$00
	and     #$0F
	jsr     mulax10
	sta     ptr1
	stx     ptr1+1
	lda     $6406
	and     #$0F
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L01A1
	inx
L01A1:	sta     _current_time+6
	stx     _current_time+6+1
	lda     $6409
	ldx     #$00
	and     #$0F
	jsr     mulax10
	sta     ptr1
	stx     ptr1+1
	lda     $6408
	and     #$0F
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L01A2
	inx
L01A2:	jsr     decax1
	sta     _current_time+8
	stx     _current_time+8+1
	lda     $640B
	ldx     #$00
	and     #$0F
	jsr     mulax10
	sta     ptr1
	stx     ptr1+1
	lda     $640A
	and     #$0F
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L01A3
	inx
L01A3:	ldy     #$64
	jsr     incaxy
	sta     _current_time+10
	stx     _current_time+10+1
	lda     $640C
	and     #$0F
	sta     _current_time+12
	stz     _current_time+12+1
	lda     #$04
	sta     $640D
	rts

.endproc

; ---------------------------------------------------------------
; __near__ unsigned long * __near__ m6242_read_timestamp (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_m6242_read_timestamp: near

.segment	"CODE"

	jsr     _m6242_read_tm
	lda     #<(_current_time)
	ldx     #>(_current_time)
	jsr     _mktime
	sta     _timestamp
	stx     _timestamp+1
	ldy     sreg
	sty     _timestamp+2
	ldy     sreg+1
	sty     _timestamp+3
	lda     #<(_timestamp)
	ldx     #>(_timestamp)
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ m6242_settime (unsigned char, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_m6242_settime: near

.segment	"CODE"

	jsr     pusha
	lda     #$05
	sta     $640D
	lda     (sp)
	jsr     pusha0
	lda     #$0A
	jsr     tosumoda0
	sta     $6400
	lda     (sp)
	jsr     pusha0
	lda     #$0A
	jsr     tosudiva0
	sta     $6401
	ldy     #$01
	lda     (sp),y
	jsr     pusha0
	lda     #$0A
	jsr     tosumoda0
	sta     $6402
	ldy     #$01
	lda     (sp),y
	jsr     pusha0
	lda     #$0A
	jsr     tosudiva0
	sta     $6403
	ldy     #$02
	lda     (sp),y
	jsr     pusha0
	lda     #$0A
	jsr     tosumoda0
	sta     $6404
	ldy     #$02
	lda     (sp),y
	jsr     pusha0
	lda     #$0A
	jsr     tosudiva0
	sta     $6405
	lda     #$04
	sta     $640D
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ m6242_setdate (unsigned char, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_m6242_setdate: near

.segment	"CODE"

	jsr     pusha
	lda     #$05
	sta     $640D
	ldy     #$02
	lda     (sp),y
	jsr     pusha0
	lda     #$0A
	jsr     tosumoda0
	sta     $6406
	ldy     #$02
	lda     (sp),y
	jsr     pusha0
	lda     #$0A
	jsr     tosudiva0
	sta     $6407
	ldy     #$01
	lda     (sp),y
	jsr     pusha0
	lda     #$0A
	jsr     tosumoda0
	sta     $6408
	ldy     #$01
	lda     (sp),y
	jsr     pusha0
	lda     #$0A
	jsr     tosudiva0
	sta     $6409
	lda     (sp)
	jsr     pusha0
	lda     #$0A
	jsr     tosumoda0
	sta     $640A
	lda     (sp)
	jsr     pusha0
	lda     #$0A
	jsr     tosudiva0
	sta     $640B
	lda     #$04
	sta     $640D
	jmp     incsp3

.endproc

