;
; File generated by cc65 v 2.17 - Git 535088fe
;
	.fopt		compiler,"cc65 v 2.17 - Git 535088fe"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_itoa
	.import		_utoa
	.import		_ultoa
	.import		_strlen
	.import		_hd44780_init
	.import		_hd44780_write
	.import		_hd44780_gotoxy
	.import		_hd44780_clrscr
	.import		_mos6551_init
	.import		_mos6551_handle_rx
	.import		_mc6840_init
	.import		_millis
	.import		_uptime
	.import		_get_geiger_pulses
	.import		_get_geiger_usv
	.import		_m6242_init
	.import		_m6242_read_time_str
	.import		_m6242_read_date_str
	.import		_key_init
	.import		_port_write
	.import		_port_tgl
	.export		_key0
	.export		_key1
	.export		_key2
	.export		_prepare_disp
	.export		_update_disp
	.export		_key0_func
	.export		_key1_func
	.export		_key2_func
	.export		_main

.segment	"DATA"

_state:
	.word	$0000
_change_state_timer:
	.dword	$00000000
_last_uptime:
	.dword	$00000000
_last_millis:
	.byte	$00

.segment	"RODATA"

L00F4:
	.byte	$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20
	.byte	$20,$20,$20,$20,$00
L00DE	:=	L00F4+0
L0073	:=	L00F4+0
L00CF	:=	L00F4+0
L00C2	:=	L00F4+0
L00AA	:=	L00F4+0
L004C:
	.byte	$50,$72,$6F,$6D,$69,$65,$6E,$69,$6F,$77,$61,$6E,$69,$65,$00
L00A3:
	.byte	$20,$75,$53,$2F,$68,$00
L005E:
	.byte	$53,$74,$61,$74,$73,$00
L00B9:
	.byte	$20,$43,$50,$4D,$00
L0055:
	.byte	$43,$7A,$61,$73,$00
L00E5:
	.byte	$55,$3A,$20,$00
L00FB:
	.byte	$42,$3A,$20,$00
L0089:
	.byte	$30,$00
L0090	:=	L0089+0
L0082:
	.byte	$2E,$00
L0097	:=	L0089+0

.segment	"BSS"

_buffer:
	.res	64,$00
_integer:
	.res	2,$00
_fraction:
	.res	2,$00
_cpmin:
	.res	2,$00
_siv:
	.res	4,$00
_key0:
	.res	5,$00
_key1:
	.res	5,$00
_key2:
	.res	5,$00

; ---------------------------------------------------------------
; void __near__ prepare_disp (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_prepare_disp: near

.segment	"CODE"

	jsr     _hd44780_clrscr
	lda     _state
	ldx     _state+1
	cpx     #$00
	bne     L0045
	cmp     #$00
	beq     L0110
	cmp     #$01
	beq     L0050
	cmp     #$02
	beq     L0059
	rts
L0110:	jsr     pusha
	jsr     _hd44780_gotoxy
	lda     #<(L004C)
	ldx     #>(L004C)
	jsr     pushax
	lda     #$0E
	jmp     _hd44780_write
L0050:	txa
	jsr     pusha
	jsr     _hd44780_gotoxy
	lda     #<(L0055)
	ldx     #>(L0055)
	jsr     pushax
	lda     #$04
	jmp     _hd44780_write
L0059:	txa
	jsr     pusha
	jsr     _hd44780_gotoxy
	lda     #<(L005E)
	ldx     #>(L005E)
	jsr     pushax
	lda     #$05
	jmp     _hd44780_write
L0045:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ update_disp (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_update_disp: near

.segment	"CODE"

	lda     _state
	ldx     _state+1
	cpx     #$00
	beq     L0112
	rts
L0112:	cmp     #$00
	beq     L0066
	cmp     #$01
	jeq     L0111
	cmp     #$02
	jeq     L00D9
	rts
L0066:	jsr     _get_geiger_pulses
	sta     _cpmin
	stx     _cpmin+1
	jsr     _get_geiger_usv
	sta     _siv
	stx     _siv+1
	ldy     sreg
	sty     _siv+2
	ldy     sreg+1
	sty     _siv+3
	lda     _siv+3
	sta     sreg+1
	lda     _siv+2
	sta     sreg
	ldx     _siv+1
	lda     _siv
	jsr     pusheax
	ldx     #$27
	lda     #$10
	jsr     tosudiv0ax
	sta     _integer
	stx     _integer+1
	lda     _siv+3
	sta     sreg+1
	lda     _siv+2
	sta     sreg
	ldx     _siv+1
	lda     _siv
	jsr     pusheax
	ldx     #$27
	lda     #$10
	jsr     tosumod0ax
	sta     _fraction
	stx     _fraction+1
	lda     #$01
	jsr     pusha
	dea
	jsr     _hd44780_gotoxy
	lda     #<(L0073)
	ldx     #>(L0073)
	jsr     pushax
	lda     #$14
	jsr     _hd44780_write
	lda     #$01
	jsr     pusha
	dea
	jsr     _hd44780_gotoxy
	lda     _integer
	ldx     _integer+1
	jsr     pushax
	lda     #<(_buffer)
	ldx     #>(_buffer)
	jsr     pushax
	ldx     #$00
	lda     #$0A
	jsr     _itoa
	lda     #<(_buffer)
	ldx     #>(_buffer)
	jsr     pushax
	lda     #<(_buffer)
	ldx     #>(_buffer)
	jsr     _strlen
	jsr     _hd44780_write
	lda     #<(L0082)
	ldx     #>(L0082)
	jsr     pushax
	lda     #$01
	jsr     _hd44780_write
	lda     _fraction+1
	cmp     #$03
	bne     L0087
	lda     _fraction
	cmp     #$E8
L0087:	bcs     L0093
	lda     #<(L0089)
	ldx     #>(L0089)
	jsr     pushax
	lda     #$01
	jsr     _hd44780_write
	lda     _fraction+1
	cmp     #$00
	bne     L008E
	lda     _fraction
	cmp     #$64
L008E:	bcs     L0093
	lda     #<(L0090)
	ldx     #>(L0090)
	jsr     pushax
	lda     #$01
	jsr     _hd44780_write
	lda     _fraction+1
	cmp     #$00
	bne     L0095
	lda     _fraction
	cmp     #$0A
L0095:	bcs     L0093
	lda     #<(L0097)
	ldx     #>(L0097)
	jsr     pushax
	lda     #$01
	jsr     _hd44780_write
L0093:	lda     _fraction
	ldx     _fraction+1
	jsr     pushax
	lda     #<(_buffer)
	ldx     #>(_buffer)
	jsr     pushax
	ldx     #$00
	lda     #$0A
	jsr     _utoa
	lda     #<(_buffer)
	ldx     #>(_buffer)
	jsr     pushax
	lda     #<(_buffer)
	ldx     #>(_buffer)
	jsr     _strlen
	jsr     _hd44780_write
	lda     #<(L00A3)
	ldx     #>(L00A3)
	jsr     pushax
	lda     #$05
	jsr     _hd44780_write
	lda     #$02
	jsr     pusha
	lda     #$00
	jsr     _hd44780_gotoxy
	lda     #<(L00AA)
	ldx     #>(L00AA)
	jsr     pushax
	lda     #$14
	jsr     _hd44780_write
	lda     #$02
	jsr     pusha
	lda     #$00
	jsr     _hd44780_gotoxy
	lda     _cpmin
	ldx     _cpmin+1
	jsr     pushax
	lda     #<(_buffer)
	ldx     #>(_buffer)
	jsr     pushax
	ldx     #$00
	lda     #$0A
	jsr     _utoa
	lda     #<(_buffer)
	ldx     #>(_buffer)
	jsr     pushax
	lda     #<(_buffer)
	ldx     #>(_buffer)
	jsr     _strlen
	jsr     _hd44780_write
	lda     #<(L00B9)
	ldx     #>(L00B9)
	jsr     pushax
	lda     #$04
	jmp     _hd44780_write
L0111:	jsr     pusha
	txa
	jsr     _hd44780_gotoxy
	lda     #<(L00C2)
	ldx     #>(L00C2)
	jsr     pushax
	lda     #$14
	jsr     _hd44780_write
	lda     #$01
	jsr     pusha
	dea
	jsr     _hd44780_gotoxy
	jsr     _m6242_read_time_str
	jsr     pushax
	lda     #$08
	jsr     _hd44780_write
	lda     #$02
	jsr     pusha
	lda     #$00
	jsr     _hd44780_gotoxy
	lda     #<(L00CF)
	ldx     #>(L00CF)
	jsr     pushax
	lda     #$14
	jsr     _hd44780_write
	lda     #$02
	jsr     pusha
	lda     #$00
	jsr     _hd44780_gotoxy
	jsr     _m6242_read_date_str
	jsr     pushax
	lda     #$08
	jmp     _hd44780_write
L00D9:	dea
	jsr     pusha
	txa
	jsr     _hd44780_gotoxy
	lda     #<(L00DE)
	ldx     #>(L00DE)
	jsr     pushax
	lda     #$14
	jsr     _hd44780_write
	lda     #$01
	jsr     pusha
	dea
	jsr     _hd44780_gotoxy
	lda     #<(L00E5)
	ldx     #>(L00E5)
	jsr     pushax
	lda     #$03
	jsr     _hd44780_write
	jsr     _uptime
	jsr     pusheax
	lda     #<(_buffer)
	ldx     #>(_buffer)
	jsr     pushax
	ldx     #$00
	lda     #$0A
	jsr     _ultoa
	lda     #<(_buffer)
	ldx     #>(_buffer)
	jsr     pushax
	lda     #<(_buffer)
	ldx     #>(_buffer)
	jsr     _strlen
	jsr     _hd44780_write
	lda     #$02
	jsr     pusha
	lda     #$00
	jsr     _hd44780_gotoxy
	lda     #<(L00F4)
	ldx     #>(L00F4)
	jsr     pushax
	lda     #$14
	jsr     _hd44780_write
	lda     #$02
	jsr     pusha
	lda     #$00
	jsr     _hd44780_gotoxy
	lda     #<(L00FB)
	ldx     #>(L00FB)
	jsr     pushax
	lda     #$03
	jsr     _hd44780_write
	lda     $6300
	jsr     pusha0
	lda     #<(_buffer)
	ldx     #>(_buffer)
	jsr     pushax
	ldx     #$00
	lda     #$0A
	jsr     _utoa
	lda     #<(_buffer)
	ldx     #>(_buffer)
	jsr     pushax
	lda     #<(_buffer)
	ldx     #>(_buffer)
	jsr     _strlen
	jmp     _hd44780_write

.endproc

; ---------------------------------------------------------------
; void __near__ key0_func (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_key0_func: near

.segment	"CODE"

	lda     #$80
	jmp     _port_tgl

.endproc

; ---------------------------------------------------------------
; void __near__ key1_func (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_key1_func: near

.segment	"CODE"

	lda     #$80
	jmp     _port_tgl

.endproc

; ---------------------------------------------------------------
; void __near__ key2_func (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_key2_func: near

.segment	"CODE"

	lda     #$10
	jmp     _port_tgl

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	lda     #$80
	jsr     _port_write
	lda     #$82
	sta     $6603
	jsr     _mc6840_init
	jsr     _m6242_init
	jsr     _mos6551_init
	jsr     _hd44780_init
	jsr     _prepare_disp
	lda     #<(_key0)
	ldx     #>(_key0)
	jsr     pushax
	lda     #$04
	jsr     pusha
	lda     #<(_key0_func)
	ldx     #>(_key0_func)
	jsr     _key_init
	lda     #<(_key1)
	ldx     #>(_key1)
	jsr     pushax
	lda     #$08
	jsr     pusha
	lda     #<(_key1_func)
	ldx     #>(_key1_func)
	jsr     _key_init
	lda     #<(_key2)
	ldx     #>(_key2)
	jsr     pushax
	lda     #$10
	jsr     pusha
	lda     #<(_key2_func)
	ldx     #>(_key2_func)
	jsr     _key_init
	cli
L0022:	jsr     _uptime
	jsr     pusheax
	lda     _last_uptime+3
	sta     sreg+1
	lda     _last_uptime+2
	sta     sreg
	ldx     _last_uptime+1
	lda     _last_uptime
	jsr     tosneeax
	beq     L0026
	jsr     _uptime
	sta     _last_uptime
	stx     _last_uptime+1
	ldy     sreg
	sty     _last_uptime+2
	ldy     sreg+1
	sty     _last_uptime+3
	jsr     _uptime
	jsr     pusheax
	lda     _change_state_timer+3
	sta     sreg+1
	lda     _change_state_timer+2
	sta     sreg
	ldx     _change_state_timer+1
	lda     _change_state_timer
	jsr     tossubeax
	cmp     #$0B
	txa
	sbc     #$00
	lda     sreg
	sbc     #$00
	lda     sreg+1
	sbc     #$00
	bcc     L002A
	jsr     _uptime
	sta     _change_state_timer
	stx     _change_state_timer+1
	ldy     sreg
	sty     _change_state_timer+2
	ldy     sreg+1
	sty     _change_state_timer+3
	lda     _state
	ldx     _state+1
	ina
	bne     L0030
	inx
L0030:	sta     _state
	stx     _state+1
	lda     _state
	cmp     #$03
	lda     _state+1
	sbc     #$00
	bvs     L0033
	eor     #$80
L0033:	bpl     L0031
	stz     _state
	stz     _state+1
L0031:	jsr     _prepare_disp
L002A:	jsr     _update_disp
L0026:	jsr     _millis
	sec
	sbc     _last_millis
	pha
	txa
	sbc     #$00
	pla
	cmp     #$0D
	bcc     L0038
	jsr     _millis
	sta     _last_millis
	lda     #$85
	jsr     _port_tgl
L0038:	jsr     _mos6551_handle_rx
	jmp     L0022

.endproc

