;
; File generated by cc65 v 2.17 - Git 535088fe
;
	.fopt		compiler,"cc65 v 2.17 - Git 535088fe"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_mc6840_init
	.export		_millis
	.export		_uptime
	.export		_get_geiger_pulses
	.export		_get_geiger_usv
	.export		_set_sound_frequency
	.export		_get_fattime
	.export		_milliseconds
	.export		_uptime_value
	.export		_geiger_ind
	.export		_geiger_pulses
	.export		_tmp16
	.export		_cpm
	.export		_tmp
	.export		_update_geiger_pulses

.segment	"DATA"

_milliseconds:
	.byte	$00
_uptime_value:
	.dword	$00000000
_geiger_ind:
	.byte	$00

.segment	"BSS"

_geiger_pulses:
	.res	120,$00
_tmp16:
	.res	2,$00
_cpm:
	.res	2,$00
_tmp:
	.res	4,$00
_i:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ mc6840_init (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_mc6840_init: near

.segment	"CODE"

	lda     #$42
	sta     $6480
	lda     #$83
	sta     $6481
	stz     $6480
	lda     #$FF
	sta     $6482
	sta     $6482+1
	ldx     #$2F
	lda     #$F8
	sta     $6484
	stx     $6484+1
	ldx     #$DF
	lda     #$B1
	sta     $6486
	stx     $6486+1
	stz     _i
L008C:	lda     _i
	cmp     #$3C
	bcs     L0033
	ldx     #$00
	lda     _i
	asl     a
	bcc     L008B
	inx
	clc
L008B:	adc     #<(_geiger_pulses)
	sta     ptr1
	txa
	adc     #>(_geiger_pulses)
	sta     ptr1+1
	lda     #$00
	sta     (ptr1)
	ldy     #$01
	sta     (ptr1),y
	inc     _i
	bra     L008C
L0033:	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ millis (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_millis: near

.segment	"CODE"

	sei
	ldx     #$00
	lda     _milliseconds
	jsr     aulong
	jsr     axulong
	sta     _tmp
	stx     _tmp+1
	ldy     sreg
	sty     _tmp+2
	ldy     sreg+1
	sty     _tmp+3
	cli
	ldx     #$00
	lda     _tmp
	rts

.endproc

; ---------------------------------------------------------------
; unsigned long __near__ uptime (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_uptime: near

.segment	"CODE"

	sei
	lda     _uptime_value+3
	sta     sreg+1
	lda     _uptime_value+2
	sta     sreg
	ldx     _uptime_value+1
	lda     _uptime_value
	sta     _tmp
	stx     _tmp+1
	ldy     sreg
	sty     _tmp+2
	ldy     sreg+1
	sty     _tmp+3
	cli
	lda     _tmp+3
	sta     sreg+1
	lda     _tmp+2
	sta     sreg
	ldx     _tmp+1
	lda     _tmp
	rts

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ get_geiger_pulses (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_get_geiger_pulses: near

.segment	"CODE"

	stz     _cpm
	stz     _cpm+1
	stz     _i
L008F:	lda     _i
	cmp     #$3C
	bcs     L006C
	ldx     #$00
	lda     _i
	asl     a
	bcc     L008E
	inx
	clc
L008E:	adc     #<(_geiger_pulses)
	tay
	txa
	adc     #>(_geiger_pulses)
	tax
	tya
	jsr     ldaxi
	clc
	adc     _cpm
	sta     _cpm
	txa
	adc     _cpm+1
	sta     _cpm+1
	inc     _i
	bra     L008F
L006C:	lda     _cpm
	ldx     _cpm+1
	rts

.endproc

; ---------------------------------------------------------------
; unsigned long __near__ get_geiger_usv (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_get_geiger_usv: near

.segment	"CODE"

	lda     _cpm
	ldx     _cpm+1
	jsr     pushax
	lda     #$39
	jsr     tosumula0
	jmp     axulong

.endproc

; ---------------------------------------------------------------
; void __near__ set_sound_frequency (unsigned int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_set_sound_frequency: near

.segment	"CODE"

	jsr     pushax
	ldy     #$01
	lda     (sp),y
	cmp     #$00
	bne     L007D
	lda     (sp)
	cmp     #$18
L007D:	bcc     L007A
	ldx     #$FF
	txa
	jsr     pushax
	ldx     #$42
	lda     #$0F
	sta     sreg
	stz     sreg+1
	lda     #$40
	jsr     pusheax
	ldy     #$07
	jsr     ldaxysp
	jsr     axulong
	jsr     tosudiveax
	jsr     tosulong
	jsr     tossubeax
	txa
	ldx     #$00
	jsr     push0ax
	dex
	txa
	jsr     pushax
	ldx     #$42
	lda     #$0F
	sta     sreg
	lda     #$40
	jsr     pusheax
	ldy     #$0B
	jsr     ldaxysp
	jsr     axulong
	jsr     tosudiveax
	jsr     tosulong
	jsr     tossubeax
	tax
	lda     #$00
	jsr     tosor0ax
	sta     $6484
	stx     $6484+1
L007A:	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; unsigned long __near__ get_fattime (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_get_fattime: near

.segment	"CODE"

	ldx     #$00
	stz     sreg
	stz     sreg+1
	txa
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ update_geiger_pulses (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_update_geiger_pulses: near

.segment	"CODE"

	sei
	lda     $6482
	sta     _tmp16+1
	lda     $6483
	sta     _tmp16
	lda     #$FF
	sta     $6482
	sta     $6482+1
	cli
	ldx     #$00
	lda     _geiger_ind
	asl     a
	bcc     L0091
	inx
	clc
L0091:	adc     #<(_geiger_pulses)
	tay
	txa
	adc     #>(_geiger_pulses)
	tax
	tya
	jsr     pushax
	ldx     #$FF
	txa
	sec
	sbc     _tmp16
	pha
	txa
	sbc     _tmp16+1
	tax
	pla
	ldy     #$00
	jsr     staxspidx
	inc     _geiger_ind
	lda     _geiger_ind
	cmp     #$3C
	bcc     L0064
	stz     _geiger_ind
L0064:	rts

.endproc

