;
; File generated by cc65 v 2.18 - Git b525554b
;
	.fopt		compiler,"cc65 v 2.18 - Git b525554b"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_cfInit
	.export		_cfReadBlocks
	.export		_cfWriteBlocks
	.export		_cfGetSizeInfo
	.export		_cfWait

; ---------------------------------------------------------------
; unsigned char __near__ cfInit (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_cfInit: near

.segment	"CODE"

	lda     #$04
	sta     $6587
	jsr     _cfWait
	lda     #$E0
	sta     $6586
	lda     #$01
	sta     $6581
	lda     #$EF
	sta     $6587
	jsr     _cfWait
	lda     $6587
	bne     L0004
	tax
	rts
L0004:	ldx     #$00
	lda     #$01
	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ cfReadBlocks (unsigned char *buffer, unsigned long lba, unsigned char blocksToRead)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_cfReadBlocks: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp1
	ldy     #$05
	jsr     ldeaxysp
	sta     $6583
	ldy     #$05
	jsr     ldeaxysp
	stx     $6584
	ldy     #$05
	jsr     ldeaxysp
	lda     sreg
	sta     $6585
	ldy     #$05
	jsr     ldeaxysp
	lda     sreg+1
	sta     (sp)
	and     #$0F
	sta     (sp)
	ora     #$E0
	sta     (sp)
	sta     $6586
	ldy     #$01
	lda     (sp),y
	sta     $6582
	jsr     _cfWait
	lda     #$20
	sta     $6587
	bra     L0007
L0002:	ldy     #$07
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     $6580
	sta     (ptr1)
	ldy     #$07
	jsr     ldaxysp
	ina
	bne     L0005
	inx
L0005:	ldy     #$06
	jsr     staxysp
L0007:	jsr     _cfWait
	lda     $6587
	and     #$08
	bne     L0002
	lda     $6587
	jsr     bnega
	ldx     #$00
	and     #$01
	beq     L0008
	txa
	bra     L0001
L0008:	ina
L0001:	jmp     incsp8

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ cfWriteBlocks (unsigned char *buffer, unsigned long lba, unsigned char blocksToWrite)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_cfWriteBlocks: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp1
	ldy     #$05
	jsr     ldeaxysp
	sta     $6583
	ldy     #$05
	jsr     ldeaxysp
	stx     $6584
	ldy     #$05
	jsr     ldeaxysp
	lda     sreg
	sta     $6585
	ldy     #$05
	jsr     ldeaxysp
	lda     sreg+1
	sta     (sp)
	and     #$0F
	sta     (sp)
	ora     #$E0
	sta     (sp)
	sta     $6586
	ldy     #$01
	lda     (sp),y
	sta     $6582
	jsr     _cfWait
	lda     #$30
	sta     $6587
	bra     L0007
L0002:	ldy     #$07
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	sta     $6580
	ldy     #$07
	jsr     ldaxysp
	ina
	bne     L0005
	inx
L0005:	ldy     #$06
	jsr     staxysp
L0007:	jsr     _cfWait
	lda     $6587
	and     #$08
	bne     L0002
	lda     $6587
	jsr     bnega
	ldx     #$00
	and     #$01
	beq     L0008
	txa
	bra     L0001
L0008:	ina
L0001:	jmp     incsp8

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ cfGetSizeInfo (unsigned long *availableBlocks, unsigned int *sizeOfBlock)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_cfGetSizeInfo: near

.segment	"CODE"

	jsr     pushax
	jsr     push0
	jsr     decsp1
	ldy     #$08
	jsr     pushwysp
	ldx     #$00
	stz     sreg
	stz     sreg+1
	txa
	tay
	jsr     steaxspidx
	jsr     _cfWait
	lda     #$EC
	sta     $6587
	jmp     L0011
L0013:	lda     $6580
	sta     (sp)
	ldy     #$02
	lda     (sp),y
	bne     L0015
	dey
	lda     (sp),y
	cmp     #$78
	bne     L0005
	ldy     #$06
	jsr     ldaxysp
	jsr     pushax
	jsr     ldeaxi
	jsr     pusheax
	ldy     #$06
	ldx     #$00
	lda     (sp),y
	jsr     axulong
	jmp     L0019
L0005:	iny
L0015:	lda     (sp),y
	bne     L0016
	dey
	lda     (sp),y
	cmp     #$79
	bne     L0008
	ldy     #$06
	jsr     ldaxysp
	jsr     pushax
	jsr     ldeaxi
	jsr     pusheax
	ldy     #$06
	ldx     #$00
	lda     (sp),y
	jsr     axulong
	ldy     sreg
	sty     sreg+1
	stx     sreg
	tax
	lda     #$00
	bra     L0019
L0008:	iny
L0016:	lda     (sp),y
	bne     L0017
	dey
	lda     (sp),y
	cmp     #$7A
	bne     L000B
	ldy     #$06
	jsr     ldaxysp
	jsr     pushax
	jsr     ldeaxi
	jsr     pusheax
	ldy     #$06
	ldx     #$00
	lda     (sp),y
	jsr     axulong
	stx     sreg+1
	sta     sreg
	lda     #$00
	tax
	bra     L0019
L000B:	iny
L0017:	lda     (sp),y
	bne     L0018
	dey
	lda     (sp),y
	cmp     #$7B
	bne     L000E
	ldy     #$06
	jsr     ldaxysp
	jsr     pushax
	jsr     ldeaxi
	jsr     pusheax
	ldy     #$06
	ldx     #$00
	lda     (sp),y
	jsr     axulong
	sta     sreg+1
	lda     #$00
	tax
	stz     sreg
L0019:	jsr     tosoreax
	ldy     #$00
	jsr     steaxspidx
L000E:	ldy     #$02
L0018:	jsr     ldaxysp
	ina
	bne     L0010
	inx
L0010:	ldy     #$01
	jsr     staxysp
L0011:	jsr     _cfWait
	lda     $6587
	and     #$08
	jne     L0013
	ldy     #$04
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	sta     (ptr1)
	ldy     #$01
	lda     #$02
	sta     (ptr1),y
	ldx     #$00
	tya
	jmp     incsp7

.endproc

; ---------------------------------------------------------------
; void __near__ cfWait (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_cfWait: near

.segment	"CODE"

L0002:	lda     $6587
	bne     L0002
	rts

.endproc

