;
; File generated by cc65 v 2.17 - Git 535088fe
;
	.fopt		compiler,"cc65 v 2.17 - Git 535088fe"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_cfInit
	.export		_cfReadBlocks
	.export		_cfWriteBlocks
	.export		_cfGetSizeInfo
	.export		_cfWait

; ---------------------------------------------------------------
; unsigned char __near__ cfInit (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_cfInit: near

.segment	"CODE"

	lda     #$04
	sta     $6587
	jsr     _cfWait
	lda     #$E0
	sta     $6586
	lda     #$01
	sta     $6581
	lda     #$EF
	sta     $6587
	jsr     _cfWait
	lda     $6587
	beq     L0018
	ldx     #$00
	lda     #$01
	rts
L0018:	ldx     #$00
	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ cfReadBlocks (__near__ unsigned char *, unsigned long, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_cfReadBlocks: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp1
	ldy     #$05
	jsr     ldeaxysp
	sta     $6583
	ldy     #$05
	jsr     ldeaxysp
	stx     $6584
	ldy     #$05
	jsr     ldeaxysp
	lda     sreg
	sta     $6585
	ldy     #$05
	jsr     ldeaxysp
	lda     sreg+1
	sta     (sp)
	and     #$0F
	sta     (sp)
	ora     #$E0
	sta     (sp)
	sta     $6586
	ldy     #$01
	lda     (sp),y
	sta     $6582
	jsr     _cfWait
	lda     #$20
	sta     $6587
	bra     L00D5
L0044:	ldy     #$07
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     $6580
	sta     (ptr1)
	ldy     #$07
	jsr     ldaxysp
	ina
	bne     L004F
	inx
L004F:	ldy     #$06
	jsr     staxysp
L00D5:	jsr     _cfWait
	lda     $6587
	and     #$08
	bne     L0044
	lda     $6587
	jsr     bnega
	ldx     #$00
	and     #$01
	beq     L00D6
	txa
	jmp     incsp8
L00D6:	ina
	jmp     incsp8

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ cfWriteBlocks (__near__ unsigned char *, unsigned long, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_cfWriteBlocks: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp1
	ldy     #$05
	jsr     ldeaxysp
	sta     $6583
	ldy     #$05
	jsr     ldeaxysp
	stx     $6584
	ldy     #$05
	jsr     ldeaxysp
	lda     sreg
	sta     $6585
	ldy     #$05
	jsr     ldeaxysp
	lda     sreg+1
	sta     (sp)
	and     #$0F
	sta     (sp)
	ora     #$E0
	sta     (sp)
	sta     $6586
	ldy     #$01
	lda     (sp),y
	sta     $6582
	jsr     _cfWait
	lda     #$30
	sta     $6587
	bra     L00D7
L007F:	ldy     #$07
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	sta     $6580
	ldy     #$07
	jsr     ldaxysp
	ina
	bne     L008A
	inx
L008A:	ldy     #$06
	jsr     staxysp
L00D7:	jsr     _cfWait
	lda     $6587
	and     #$08
	bne     L007F
	lda     $6587
	jsr     bnega
	ldx     #$00
	and     #$01
	beq     L00D8
	txa
	jmp     incsp8
L00D8:	ina
	jmp     incsp8

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ cfGetSizeInfo (__near__ unsigned long *, __near__ unsigned int *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_cfGetSizeInfo: near

.segment	"CODE"

	jsr     pushax
	jsr     push0
	jsr     decsp1
	ldy     #$08
	jsr     pushwysp
	ldx     #$00
	stz     sreg
	stz     sreg+1
	txa
	tay
	jsr     steaxspidx
	jsr     _cfWait
	lda     #$EC
	sta     $6587
	jmp     L00D9
L00DB:	lda     $6580
	sta     (sp)
	ldy     #$02
	lda     (sp),y
	bne     L00DD
	dey
	lda     (sp),y
	cmp     #$78
	bne     L00A6
	ldy     #$06
	jsr     ldaxysp
	jsr     pushax
	jsr     ldeaxi
	jsr     pusheax
	ldy     #$06
	ldx     #$00
	lda     (sp),y
	jsr     aulong
	jsr     axulong
	jmp     L00E1
L00A6:	iny
L00DD:	lda     (sp),y
	bne     L00DE
	dey
	lda     (sp),y
	cmp     #$79
	bne     L00AC
	ldy     #$06
	jsr     ldaxysp
	jsr     pushax
	jsr     ldeaxi
	jsr     pusheax
	ldy     #$06
	ldx     #$00
	lda     (sp),y
	jsr     aulong
	jsr     axulong
	ldy     sreg
	sty     sreg+1
	stx     sreg
	tax
	lda     #$00
	bra     L00E1
L00AC:	iny
L00DE:	lda     (sp),y
	bne     L00DF
	dey
	lda     (sp),y
	cmp     #$7A
	bne     L00B3
	ldy     #$06
	jsr     ldaxysp
	jsr     pushax
	jsr     ldeaxi
	jsr     pusheax
	ldy     #$06
	ldx     #$00
	lda     (sp),y
	jsr     aulong
	jsr     axulong
	stx     sreg+1
	sta     sreg
	lda     #$00
	tax
	bra     L00E1
L00B3:	iny
L00DF:	lda     (sp),y
	bne     L00E0
	dey
	lda     (sp),y
	cmp     #$7B
	bne     L00BA
	ldy     #$06
	jsr     ldaxysp
	jsr     pushax
	jsr     ldeaxi
	jsr     pusheax
	ldy     #$06
	ldx     #$00
	lda     (sp),y
	jsr     aulong
	jsr     axulong
	sta     sreg+1
	lda     #$00
	tax
	stz     sreg
L00E1:	jsr     tosoreax
	ldy     #$00
	jsr     steaxspidx
L00BA:	ldy     #$02
L00E0:	jsr     ldaxysp
	ina
	bne     L00C1
	inx
L00C1:	ldy     #$01
	jsr     staxysp
L00D9:	jsr     _cfWait
	lda     $6587
	and     #$08
	jne     L00DB
	ldy     #$04
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	sta     (ptr1)
	ldy     #$01
	lda     #$02
	sta     (ptr1),y
	ldx     #$00
	tya
	jmp     incsp7

.endproc

; ---------------------------------------------------------------
; void __near__ cfWait (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_cfWait: near

.segment	"CODE"

L00C7:	lda     $6587
	bne     L00C7
	rts

.endproc

