;
; File generated by cc65 v 2.18 - Git b525554b
;
	.fopt		compiler,"cc65 v 2.18 - Git b525554b"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_disk_initialize
	.export		_disk_status
	.export		_disk_read
	.export		_disk_write
	.export		_disk_ioctl
	.import		_cfInit
	.import		_cfReadBlocks
	.import		_cfWriteBlocks
	.import		_cfGetSizeInfo

.segment	"DATA"

_diskStatus:
	.byte	$01

; ---------------------------------------------------------------
; unsigned char __near__ disk_initialize (unsigned char drv)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_disk_initialize: near

.segment	"CODE"

	jsr     pusha
	ldx     #$00
	lda     (sp)
	bne     L0003
	jsr     _cfInit
	cmp     #$00
	beq     L0007
	lda     #$01
L0007:	sta     _diskStatus
	ldx     #$00
	lda     _diskStatus
L0003:	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ disk_status (unsigned char drv)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_disk_status: near

.segment	"CODE"

	jsr     pusha
	ldx     #$00
	lda     (sp)
	bne     L0005
	lda     _diskStatus
	bra     L0001
L0005:	txa
L0001:	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; enum $anon-enum-0009 __near__ disk_read (unsigned char drv, unsigned char *buff, unsigned long sector, unsigned char count)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_disk_read: near

.segment	"CODE"

	jsr     pusha
	ldy     #$07
	ldx     #$00
	lda     (sp),y
	bne     L0003
	iny
	jsr     pushwysp
	ldy     #$06
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$06
	lda     (sp),y
	jsr     _cfReadBlocks
	ldx     #$00
	txa
L0003:	jmp     incsp8

.endproc

; ---------------------------------------------------------------
; enum $anon-enum-0009 __near__ disk_write (unsigned char drv, const unsigned char *buff, unsigned long sector, unsigned char count)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_disk_write: near

.segment	"CODE"

	jsr     pusha
	ldy     #$07
	ldx     #$00
	lda     (sp),y
	bne     L0003
	iny
	jsr     pushwysp
	ldy     #$06
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$06
	lda     (sp),y
	jsr     _cfWriteBlocks
	ldx     #$00
	txa
L0003:	jmp     incsp8

.endproc

; ---------------------------------------------------------------
; enum $anon-enum-0009 __near__ disk_ioctl (unsigned char drv, unsigned char ctrl, void *buff)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_disk_ioctl: near

.segment	"CODE"

	jsr     pushax
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	bne     L0003
	dey
	lda     (sp),y
	beq     L0003
	cmp     #$01
	beq     L0007
	cmp     #$03
	beq     L0008
	bra     L000D
L0007:	lda     #<(M0001)
	ldx     #>(M0001)
	jsr     pushax
	lda     #<(M0002)
	ldx     #>(M0002)
	jsr     _cfGetSizeInfo
	lda     #<(M0001)
	ldx     #>(M0001)
	jsr     stax0sp
	ldx     #$00
	txa
	bra     L0003
L0008:	lda     #<(M0001)
	ldx     #>(M0001)
	jsr     pushax
	lda     #<(M0002)
	ldx     #>(M0002)
	jsr     _cfGetSizeInfo
	lda     #<(M0002)
	ldx     #>(M0002)
	jsr     stax0sp
	ldx     #$00
	txa
	bra     L0003
L000D:	lda     #$01
L0003:	jmp     incsp4

.segment	"BSS"

M0001:
	.res	4,$00
M0002:
	.res	2,$00

.endproc

