;
; File generated by cc65 v 2.17 - Git 535088fe
;
	.fopt		compiler,"cc65 v 2.17 - Git 535088fe"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_disk_initialize
	.export		_disk_status
	.export		_disk_read
	.export		_disk_write
	.export		_disk_ioctl
	.import		_cfInit
	.import		_cfReadBlocks
	.import		_cfWriteBlocks
	.import		_cfGetSizeInfo

.segment	"DATA"

_diskStatus:
	.byte	$01

; ---------------------------------------------------------------
; unsigned char __near__ disk_initialize (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_disk_initialize: near

.segment	"CODE"

	jsr     pusha
	ldx     #$00
	lda     (sp)
	bne     L000B
	jsr     _cfInit
	cmp     #$00
	beq     L0057
	lda     #$01
L0057:	sta     _diskStatus
	ldx     #$00
	lda     _diskStatus
	jmp     incsp1
L000B:	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ disk_status (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_disk_status: near

.segment	"CODE"

	jsr     pusha
	ldx     #$00
	lda     (sp)
	bne     L0058
	lda     _diskStatus
	jmp     incsp1
L0058:	txa
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; int __near__ disk_read (unsigned char, __near__ unsigned char *, unsigned long, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_disk_read: near

.segment	"CODE"

	jsr     pusha
	ldy     #$07
	ldx     #$00
	lda     (sp),y
	bne     L0022
	iny
	jsr     pushwysp
	ldy     #$06
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$06
	lda     (sp),y
	jsr     _cfReadBlocks
	ldx     #$00
	txa
	jmp     incsp8
L0022:	jmp     incsp8

.endproc

; ---------------------------------------------------------------
; int __near__ disk_write (unsigned char, __near__ const unsigned char *, unsigned long, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_disk_write: near

.segment	"CODE"

	jsr     pusha
	ldy     #$07
	ldx     #$00
	lda     (sp),y
	bne     L002E
	iny
	jsr     pushwysp
	ldy     #$06
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$06
	lda     (sp),y
	jsr     _cfWriteBlocks
	ldx     #$00
	txa
	jmp     incsp8
L002E:	jmp     incsp8

.endproc

; ---------------------------------------------------------------
; int __near__ disk_ioctl (unsigned char, unsigned char, __near__ void *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_disk_ioctl: near

.segment	"BSS"

L0038:
	.res	4,$00
L0039:
	.res	2,$00

.segment	"CODE"

	jsr     pushax
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	bne     L003C
	dey
	lda     (sp),y
	beq     L003C
	cmp     #$01
	beq     L0043
	cmp     #$03
	beq     L004B
	bra     L005B
L0043:	lda     #<(L0038)
	ldx     #>(L0038)
	jsr     pushax
	lda     #<(L0039)
	ldx     #>(L0039)
	jsr     _cfGetSizeInfo
	lda     #<(L0038)
	ldx     #>(L0038)
	jsr     stax0sp
	ldx     #$00
	txa
	jmp     incsp4
L004B:	lda     #<(L0038)
	ldx     #>(L0038)
	jsr     pushax
	lda     #<(L0039)
	ldx     #>(L0039)
	jsr     _cfGetSizeInfo
	lda     #<(L0039)
	ldx     #>(L0039)
	jsr     stax0sp
	ldx     #$00
	txa
	jmp     incsp4
L005B:	lda     #$01
	jmp     incsp4
L003C:	jmp     incsp4

.endproc

