;
; File generated by cc65 v 2.18 - Git b525554b
;
	.fopt		compiler,"cc65 v 2.18 - Git b525554b"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_hd44780_init
	.export		_hd44780_putc
	.export		_hd44780_write
	.export		_hd44780_puts
	.export		_hd44780_gotoxy
	.export		_hd44780_clrscr
	.import		_delay_16us
	.import		_delay_ms

.segment	"RODATA"

S0001:
	.byte	$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20
	.byte	$20,$20,$20,$20,$00

; ---------------------------------------------------------------
; void __near__ __fastcall__ hd44780_init (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_hd44780_init: near

.segment	"CODE"

	lda     #$64
	jsr     _delay_ms
	lda     #$30
	sta     $6380
	lda     #$64
	jsr     _delay_ms
	lda     #$30
	sta     $6380
	lda     #$07
	jsr     _delay_16us
	lda     #$30
	sta     $6380
	lda     #$07
	jsr     _delay_16us
L0011:	lda     $6380
	and     #$80
	bne     L0011
	lda     #$38
	sta     $6380
L0012:	lda     $6380
	and     #$80
	bne     L0012
	lda     #$08
	sta     $6380
L0013:	lda     $6380
	and     #$80
	bne     L0013
	ina
	sta     $6380
L0014:	lda     $6380
	and     #$80
	bne     L0014
	lda     #$06
	sta     $6380
L0015:	lda     $6380
	and     #$80
	bne     L0015
	lda     #$0C
	sta     $6380
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ __fastcall__ hd44780_putc (char c)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_hd44780_putc: near

.segment	"CODE"

	jsr     pusha
L0005:	lda     $6380
	and     #$80
	bne     L0005
	lda     (sp)
	sta     $6381
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ __fastcall__ hd44780_write (unsigned char *buf, unsigned char len)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_hd44780_write: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp1
	lda     #$00
L000C:	sta     (sp)
	ldy     #$01
	cmp     (sp),y
	bcs     L0003
L000B:	lda     $6380
	and     #$80
	bne     L000B
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (sp)
	tay
	lda     (ptr1),y
	sta     $6381
	lda     (sp)
	ina
	bra     L000C
L0003:	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ __fastcall__ hd44780_puts (const char *str)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_hd44780_puts: near

.segment	"CODE"

	jsr     pushax
	bra     L0004
L0009:	lda     $6380
	and     #$80
	bne     L0009
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	sta     $6381
	jsr     ldax0sp
	ina
	bne     L0008
	inx
L0008:	jsr     stax0sp
L0004:	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	bne     L0009
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ __fastcall__ hd44780_gotoxy (unsigned char x, unsigned char y)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_hd44780_gotoxy: near

.segment	"CODE"

	jsr     pusha
	lda     #$00
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	bne     L000F
	lda     #$80
	bra     L0015
L000F:	lda     (sp),y
	cmp     #$01
	bne     L0011
	lda     #$C0
	bra     L0015
L0011:	lda     (sp),y
	cmp     #$02
	bne     L0013
	lda     #$94
	bra     L0015
L0013:	lda     (sp),y
	cmp     #$03
	bne     L0008
	lda     #$D4
L0015:	sta     (sp)
L0008:	dey
	lda     (sp),y
	cmp     #$14
	bcs     L0014
	clc
	adc     (sp)
	sta     (sp)
L0014:	lda     $6380
	and     #$80
	bne     L0014
	lda     (sp)
	sta     $6380
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ __fastcall__ hd44780_clrscr (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_hd44780_clrscr: near

.segment	"CODE"

	jsr     decsp1
	lda     #$00
L0008:	sta     (sp)
	cmp     #$04
	bcs     L0003
	lda     (sp)
	jsr     pusha
	lda     #$00
	jsr     _hd44780_gotoxy
	lda     #<(S0001)
	ldx     #>(S0001)
	jsr     _hd44780_puts
	lda     (sp)
	ina
	bra     L0008
L0003:	jmp     incsp1

.endproc

