;
; File generated by cc65 v 2.18 - Git b525554b
;
	.fopt		compiler,"cc65 v 2.18 - Git b525554b"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_atoi
	.import		_ultoa
	.import		_strchr
	.import		_strtok
	.import		_strcasecmp
	.export		_parse_cmd
	.import		_uptime
	.import		_mos6551_puts
	.import		_m6242_read_time_str
	.import		_m6242_read_date_str
	.import		_m6242_settime
	.import		_m6242_setdate
	.export		_komendy

.segment	"RODATA"

_komendy:
	.byte	$73,$65,$74,$74,$69,$6D,$65,$00
	.res	4,$00
	.addr	_settime_service
	.byte	$67,$65,$74,$74,$69,$6D,$65,$00
	.res	4,$00
	.addr	_gettime_service
	.byte	$73,$65,$74,$64,$61,$74,$65,$00
	.res	4,$00
	.addr	_setdate_service
	.byte	$67,$65,$74,$64,$61,$74,$65,$00
	.res	4,$00
	.addr	_getdate_service
	.byte	$75,$70,$74,$69,$6D,$65,$00
	.res	5,$00
	.addr	_uptime_service
S000B:
	.byte	$49,$6E,$76,$61,$6C,$69,$64,$20,$6F,$72,$20,$6D,$69,$73,$73,$69
	.byte	$6E,$67,$20,$70,$61,$72,$61,$6D,$65,$74,$65,$72,$0D,$0A,$00
S0008	:=	S000B+0
S000D:
	.byte	$55,$6E,$6B,$6E,$6F,$77,$6E,$20,$63,$6F,$6D,$6D,$61,$6E,$64,$0D
	.byte	$0A,$00
S000A	:=	S000D+0
S000C:
	.byte	$4F,$4B,$0D,$0A,$00
S0009	:=	S000C+0
S0016	:=	S000B+28
S0015	:=	S000B+28
S0011	:=	S000B+28
S0006:
	.byte	$20,$00,$00
S000F:
	.byte	$3A,$00
S0012:
	.byte	$2D,$00
S0013	:=	S0012+0
S0014	:=	S0012+0
S000E	:=	S000F+0
S0007:
	.byte	$20,$00
S0010	:=	S000F+0

; ---------------------------------------------------------------
; void __near__ parse_cmd (char *pBuf)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_parse_cmd: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp3
	ldy     #$06
	jsr     pushwysp
	ldx     #$00
	lda     #$20
	jsr     _strchr
	stx     tmp1
	ora     tmp1
	jeq     L0018
	ldy     #$06
	jsr     pushwysp
	lda     #<(S0006)
	ldx     #>(S0006)
	jsr     _strtok
	ldy     #$01
	jsr     staxysp
	lda     #$00
L0017:	sta     (sp)
	cmp     #$05
	jcs     L0004
	jsr     push0
	ldy     #$06
	jsr     pushwysp
	ldy     #$04
	lda     (sp),y
	jsr     pusha0
	lda     #$0E
	jsr     tosmula0
	clc
	adc     #<(_komendy)
	tay
	txa
	adc     #>(_komendy)
	tax
	tya
	jsr     _strcasecmp
	jsr     tosicmp
	bne     L0005
	jsr     push0
	lda     #<(S0007)
	ldx     #>(S0007)
	jsr     _strtok
	ldy     #$01
	jsr     staxysp
	jsr     push0
	ldy     #$02
	lda     (sp),y
	jsr     pusha0
	lda     #$0E
	jsr     tosmula0
	clc
	adc     #<(_komendy)
	tay
	txa
	adc     #>(_komendy)
	tax
	tya
	ldy     #$0D
	jsr     pushwidx
	ldy     #$06
	jsr     ldaxysp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	jsr     tosicmp
	bne     L0008
	lda     #<(S0008)
	ldx     #>(S0008)
	jmp     L0012
L0008:	lda     #<(S0009)
	ldx     #>(S0009)
	jmp     L0012
L0005:	lda     (sp)
	ina
	jmp     L0017
L0004:	lda     #<(S000A)
	ldx     #>(S000A)
	bra     L0012
L0018:	sta     (sp)
	cmp     #$05
	bcs     L000C
	jsr     push0
	ldy     #$08
	jsr     pushwysp
	ldy     #$04
	lda     (sp),y
	jsr     pusha0
	lda     #$0E
	jsr     tosmula0
	clc
	adc     #<(_komendy)
	tay
	txa
	adc     #>(_komendy)
	tax
	tya
	jsr     _strcasecmp
	jsr     tosicmp
	bne     L000D
	jsr     push0
	ldy     #$02
	lda     (sp),y
	jsr     pusha0
	lda     #$0E
	jsr     tosmula0
	clc
	adc     #<(_komendy)
	tay
	txa
	adc     #>(_komendy)
	tax
	tya
	ldy     #$0D
	jsr     pushwidx
	ldx     #$00
	txa
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	jsr     tosicmp
	bne     L0010
	lda     #<(S000B)
	ldx     #>(S000B)
	bra     L0012
L0010:	lda     #<(S000C)
	ldx     #>(S000C)
	bra     L0012
L000D:	lda     (sp)
	ina
	bra     L0018
L000C:	lda     #<(S000D)
	ldx     #>(S000D)
L0012:	jsr     _mos6551_puts
	jmp     incsp5

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ settime_service (char *params)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_settime_service: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp6
	ldy     #$07
	lda     (sp),y
	dey
	ora     (sp),y
	bne     L0002
	tax
	jmp     L0001
L0002:	ldy     #$09
	jsr     pushwysp
	lda     #<(S000E)
	ldx     #>(S000E)
	jsr     _strtok
	ldy     #$04
	jsr     staxysp
	ldy     #$05
	lda     (sp),y
	dey
	ora     (sp),y
	bne     L0003
	tax
	jmp     L0001
L0003:	iny
	jsr     ldaxysp
	jsr     _atoi
	cmp     #$80
	sta     (sp)
	sec
	sbc     #$01
	bvc     L0007
	eor     #$80
L0007:	bmi     L001C
	lda     (sp)
	sec
	sbc     #$18
	bvs     L000A
	eor     #$80
L000A:	bmi     L001C
	bra     L001E
L001C:	ldx     #$00
	txa
	jmp     L0001
L001E:	jsr     push0
	lda     #<(S000F)
	ldx     #>(S000F)
	jsr     _strtok
	ldy     #$04
	jsr     staxysp
	ldy     #$05
	lda     (sp),y
	dey
	ora     (sp),y
	bne     L000C
	tax
	bra     L0001
L000C:	iny
	jsr     ldaxysp
	jsr     _atoi
	cmp     #$80
	ldy     #$01
	sta     (sp),y
	asl     a
	bcs     L001F
	lda     (sp),y
	sec
	sbc     #$3C
	bvs     L0012
	eor     #$80
L0012:	bmi     L001F
	bra     L0021
L001F:	ldx     #$00
	txa
	bra     L0001
L0021:	jsr     push0
	lda     #<(S0010)
	ldx     #>(S0010)
	jsr     _strtok
	ldy     #$04
	jsr     staxysp
	ldy     #$05
	lda     (sp),y
	dey
	ora     (sp),y
	bne     L0014
	tax
	bra     L0001
L0014:	iny
	jsr     ldaxysp
	jsr     _atoi
	cmp     #$80
	ldy     #$02
	sta     (sp),y
	asl     a
	bcs     L0022
	lda     (sp),y
	sec
	sbc     #$3C
	bvs     L001A
	eor     #$80
L001A:	bpl     L0016
L0022:	ldx     #$00
	txa
	bra     L0001
L0016:	lda     (sp)
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	jsr     _m6242_settime
	ldx     #$00
	lda     #$01
L0001:	jmp     incsp8

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ gettime_service (char *params)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_gettime_service: near

.segment	"CODE"

	jsr     pushax
	jsr     _m6242_read_time_str
	jsr     _mos6551_puts
	lda     #<(S0011)
	ldx     #>(S0011)
	jsr     _mos6551_puts
	ldx     #$00
	lda     #$01
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ setdate_service (char *params)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_setdate_service: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp6
	ldy     #$07
	lda     (sp),y
	dey
	ora     (sp),y
	bne     L0002
	tax
	jmp     L0001
L0002:	ldy     #$09
	jsr     pushwysp
	lda     #<(S0012)
	ldx     #>(S0012)
	jsr     _strtok
	ldy     #$04
	jsr     staxysp
	ldy     #$05
	lda     (sp),y
	dey
	ora     (sp),y
	bne     L0003
	tax
	jmp     L0001
L0003:	iny
	jsr     ldaxysp
	jsr     _atoi
	cmp     #$80
	sta     (sp)
	sec
	sbc     #$01
	bvc     L0007
	eor     #$80
L0007:	bmi     L001D
	lda     (sp)
	sec
	sbc     #$20
	bvs     L000A
	eor     #$80
L000A:	bmi     L001D
	bra     L001F
L001D:	ldx     #$00
	txa
	jmp     L0001
L001F:	jsr     push0
	lda     #<(S0013)
	ldx     #>(S0013)
	jsr     _strtok
	ldy     #$04
	jsr     staxysp
	ldy     #$05
	lda     (sp),y
	dey
	ora     (sp),y
	bne     L000C
	tax
	bra     L0001
L000C:	iny
	jsr     ldaxysp
	jsr     _atoi
	cmp     #$80
	ldy     #$01
	sta     (sp),y
	sec
	sbc     #$01
	bvc     L0010
	eor     #$80
L0010:	bmi     L0020
	lda     (sp),y
	sec
	sbc     #$0D
	bvs     L0013
	eor     #$80
L0013:	bmi     L0020
	bra     L0022
L0020:	ldx     #$00
	txa
	bra     L0001
L0022:	jsr     push0
	lda     #<(S0014)
	ldx     #>(S0014)
	jsr     _strtok
	ldy     #$04
	jsr     staxysp
	ldy     #$05
	lda     (sp),y
	dey
	ora     (sp),y
	bne     L0015
	tax
	bra     L0001
L0015:	iny
	jsr     ldaxysp
	jsr     _atoi
	cmp     #$80
	ldy     #$02
	sta     (sp),y
	asl     a
	bcs     L0023
	lda     (sp),y
	sec
	sbc     #$64
	bvs     L001B
	eor     #$80
L001B:	bpl     L0017
L0023:	ldx     #$00
	txa
	bra     L0001
L0017:	lda     (sp)
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	jsr     _m6242_setdate
	ldx     #$00
	lda     #$01
L0001:	jmp     incsp8

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ getdate_service (char *params)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_getdate_service: near

.segment	"CODE"

	jsr     pushax
	jsr     _m6242_read_date_str
	jsr     _mos6551_puts
	lda     #<(S0015)
	ldx     #>(S0015)
	jsr     _mos6551_puts
	ldx     #$00
	lda     #$01
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ uptime_service (char *params)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_uptime_service: near

.segment	"CODE"

	jsr     pushax
	ldy     #$0F
	jsr     subysp
	jsr     _uptime
	jsr     pusheax
	lda     #$04
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$0A
	jsr     _ultoa
	lda     sp
	ldx     sp+1
	jsr     _mos6551_puts
	lda     #<(S0016)
	ldx     #>(S0016)
	jsr     _mos6551_puts
	ldx     #$00
	lda     #$01
	ldy     #$11
	jmp     addysp

.endproc

