;
; File generated by cc65 v 2.17 - Git 535088fe
;
	.fopt		compiler,"cc65 v 2.17 - Git 535088fe"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_atoi
	.import		_ultoa
	.import		_strchr
	.import		_strtok
	.import		_strcasecmp
	.export		_parse_cmd
	.import		_uptime
	.import		_mos6551_puts
	.import		_m6242_read_time_str
	.import		_m6242_read_date_str
	.import		_m6242_settime
	.import		_m6242_setdate
	.export		_komendy
	.export		_supbuf
	.export		_i
	.export		_tok

.segment	"RODATA"

_komendy:
	.byte	$73,$65,$74,$74,$69,$6D,$65,$00
	.res	4,$00
	.addr	_settime_service
	.byte	$67,$65,$74,$74,$69,$6D,$65,$00
	.res	4,$00
	.addr	_gettime_service
	.byte	$73,$65,$74,$64,$61,$74,$65,$00
	.res	4,$00
	.addr	_setdate_service
	.byte	$67,$65,$74,$64,$61,$74,$65,$00
	.res	4,$00
	.addr	_getdate_service
	.byte	$75,$70,$74,$69,$6D,$65,$00
	.res	5,$00
	.addr	_uptime_service
L004D:
	.byte	$49,$6E,$76,$61,$6C,$69,$64,$20,$6F,$72,$20,$6D,$69,$73,$73,$69
	.byte	$6E,$67,$20,$70,$61,$72,$61,$6D,$65,$74,$65,$72,$0D,$0A,$00
L0031	:=	L004D+0
L0054:
	.byte	$55,$6E,$6B,$6E,$6F,$77,$6E,$20,$63,$6F,$6D,$6D,$61,$6E,$64,$0D
	.byte	$0A,$00
L0038	:=	L0054+0
L0051:
	.byte	$4F,$4B,$0D,$0A,$00
L0035	:=	L0051+0
L0117	:=	L004D+28
L010C	:=	L004D+28
L00AF	:=	L004D+28
L0018:
	.byte	$20,$00,$00
L0076:
	.byte	$3A,$00
L00B9:
	.byte	$2D,$00
L00D2	:=	L00B9+0
L00EB	:=	L00B9+0
L005D	:=	L0076+0
L002A:
	.byte	$20,$00
L008E	:=	L0076+0

.segment	"BSS"

_supbuf:
	.res	15,$00
_i:
	.res	1,$00
_tok:
	.res	2,$00

; ---------------------------------------------------------------
; void __near__ parse_cmd (__near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_parse_cmd: near

.segment	"CODE"

	jsr     pushax
	jsr     pushw0sp
	ldx     #$00
	lda     #$20
	jsr     _strchr
	stx     tmp1
	ora     tmp1
	jeq     L0011
	jsr     pushw0sp
	lda     #<(L0018)
	ldx     #>(L0018)
	jsr     _strtok
	sta     _tok
	stx     _tok+1
	stz     _i
L011B:	lda     _i
	cmp     #$05
	jcs     L001B
	jsr     push0
	lda     _tok
	ldx     _tok+1
	jsr     pushax
	lda     _i
	jsr     pusha0
	lda     #$0E
	jsr     tosmula0
	clc
	adc     #<(_komendy)
	tay
	txa
	adc     #>(_komendy)
	tax
	tya
	jsr     _strcasecmp
	jsr     tosicmp
	bne     L001C
	jsr     push0
	lda     #<(L002A)
	ldx     #>(L002A)
	jsr     _strtok
	sta     _tok
	stx     _tok+1
	jsr     push0
	lda     _i
	jsr     pusha0
	lda     #$0E
	jsr     tosmula0
	clc
	adc     #<(_komendy)
	tay
	txa
	adc     #>(_komendy)
	tax
	tya
	ldy     #$0D
	jsr     pushwidx
	lda     _tok
	ldx     _tok+1
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	jsr     tosicmp
	bne     L002C
	lda     #<(L0031)
	ldx     #>(L0031)
	jmp     L011A
L002C:	lda     #<(L0035)
	ldx     #>(L0035)
	jmp     L011A
L001C:	inc     _i
	jmp     L011B
L001B:	lda     #<(L0038)
	ldx     #>(L0038)
	bra     L011A
L0011:	stz     _i
L011C:	lda     _i
	cmp     #$05
	bcs     L003C
	jsr     push0
	ldy     #$05
	jsr     pushwysp
	lda     _i
	jsr     pusha0
	lda     #$0E
	jsr     tosmula0
	clc
	adc     #<(_komendy)
	tay
	txa
	adc     #>(_komendy)
	tax
	tya
	jsr     _strcasecmp
	jsr     tosicmp
	bne     L003D
	jsr     push0
	lda     _i
	jsr     pusha0
	lda     #$0E
	jsr     tosmula0
	clc
	adc     #<(_komendy)
	tay
	txa
	adc     #>(_komendy)
	tax
	tya
	ldy     #$0D
	jsr     pushwidx
	ldx     #$00
	txa
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	jsr     tosicmp
	bne     L0048
	lda     #<(L004D)
	ldx     #>(L004D)
	bra     L011A
L0048:	lda     #<(L0051)
	ldx     #>(L0051)
	bra     L011A
L003D:	inc     _i
	bra     L011C
L003C:	lda     #<(L0054)
	ldx     #>(L0054)
L011A:	jsr     _mos6551_puts
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ settime_service (__near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_settime_service: near

.segment	"CODE"

	jsr     pushax
	ldy     #$01
	lda     (sp),y
	ora     (sp)
	bne     L0057
	tax
	jmp     incsp2
L0057:	jsr     pushw0sp
	lda     #<(L005D)
	ldx     #>(L005D)
	jsr     _strtok
	sta     _tok
	stx     _tok+1
	lda     _tok
	ora     _tok+1
	bne     L005F
	tax
	jmp     incsp2
L005F:	lda     _tok
	ldx     _tok+1
	jsr     _atoi
	cmp     #$80
	sta     _supbuf
	sec
	sbc     #$01
	bvc     L006C
	eor     #$80
L006C:	bmi     L011D
	lda     _supbuf
	sec
	sbc     #$18
	bvs     L0070
	eor     #$80
L0070:	bmi     L011D
	bra     L011F
L011D:	ldx     #$00
	txa
	jmp     incsp2
L011F:	jsr     push0
	lda     #<(L0076)
	ldx     #>(L0076)
	jsr     _strtok
	sta     _tok
	stx     _tok+1
	lda     _tok
	ora     _tok+1
	bne     L0078
	tax
	jmp     incsp2
L0078:	lda     _tok
	ldx     _tok+1
	jsr     _atoi
	cmp     #$80
	sta     _supbuf+1
	asl     a
	bcs     L0120
	lda     _supbuf+1
	sec
	sbc     #$3C
	bvs     L0088
	eor     #$80
L0088:	bmi     L0120
	bra     L0122
L0120:	ldx     #$00
	txa
	jmp     incsp2
L0122:	jsr     push0
	lda     #<(L008E)
	ldx     #>(L008E)
	jsr     _strtok
	sta     _tok
	stx     _tok+1
	lda     _tok
	ora     _tok+1
	bne     L0090
	tax
	jmp     incsp2
L0090:	lda     _tok
	ldx     _tok+1
	jsr     _atoi
	cmp     #$80
	sta     _supbuf+2
	asl     a
	bcs     L0123
	lda     _supbuf+2
	sec
	sbc     #$3C
	bvs     L00A0
	eor     #$80
L00A0:	bpl     L0098
L0123:	ldx     #$00
	txa
	jmp     incsp2
L0098:	lda     _supbuf
	jsr     pusha
	lda     _supbuf+1
	jsr     pusha
	lda     _supbuf+2
	jsr     _m6242_settime
	ldx     #$00
	lda     #$01
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ gettime_service (__near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_gettime_service: near

.segment	"CODE"

	jsr     pushax
	jsr     _m6242_read_time_str
	jsr     _mos6551_puts
	lda     #<(L00AF)
	ldx     #>(L00AF)
	jsr     _mos6551_puts
	ldx     #$00
	lda     #$01
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ setdate_service (__near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_setdate_service: near

.segment	"CODE"

	jsr     pushax
	ldy     #$01
	lda     (sp),y
	ora     (sp)
	bne     L00B3
	tax
	jmp     incsp2
L00B3:	jsr     pushw0sp
	lda     #<(L00B9)
	ldx     #>(L00B9)
	jsr     _strtok
	sta     _tok
	stx     _tok+1
	lda     _tok
	ora     _tok+1
	bne     L00BB
	tax
	jmp     incsp2
L00BB:	lda     _tok
	ldx     _tok+1
	jsr     _atoi
	cmp     #$80
	sta     _supbuf
	sec
	sbc     #$01
	bvc     L00C8
	eor     #$80
L00C8:	bmi     L0124
	lda     _supbuf
	sec
	sbc     #$20
	bvs     L00CC
	eor     #$80
L00CC:	bmi     L0124
	bra     L0126
L0124:	ldx     #$00
	txa
	jmp     incsp2
L0126:	jsr     push0
	lda     #<(L00D2)
	ldx     #>(L00D2)
	jsr     _strtok
	sta     _tok
	stx     _tok+1
	lda     _tok
	ora     _tok+1
	bne     L00D4
	tax
	jmp     incsp2
L00D4:	lda     _tok
	ldx     _tok+1
	jsr     _atoi
	cmp     #$80
	sta     _supbuf+1
	sec
	sbc     #$01
	bvc     L00E1
	eor     #$80
L00E1:	bmi     L0127
	lda     _supbuf+1
	sec
	sbc     #$0D
	bvs     L00E5
	eor     #$80
L00E5:	bmi     L0127
	bra     L0129
L0127:	ldx     #$00
	txa
	jmp     incsp2
L0129:	jsr     push0
	lda     #<(L00EB)
	ldx     #>(L00EB)
	jsr     _strtok
	sta     _tok
	stx     _tok+1
	lda     _tok
	ora     _tok+1
	bne     L00ED
	tax
	jmp     incsp2
L00ED:	lda     _tok
	ldx     _tok+1
	jsr     _atoi
	cmp     #$80
	sta     _supbuf+2
	asl     a
	bcs     L012A
	lda     _supbuf+2
	sec
	sbc     #$64
	bvs     L00FD
	eor     #$80
L00FD:	bpl     L00F5
L012A:	ldx     #$00
	txa
	jmp     incsp2
L00F5:	lda     _supbuf
	jsr     pusha
	lda     _supbuf+1
	jsr     pusha
	lda     _supbuf+2
	jsr     _m6242_setdate
	ldx     #$00
	lda     #$01
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ getdate_service (__near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_getdate_service: near

.segment	"CODE"

	jsr     pushax
	jsr     _m6242_read_date_str
	jsr     _mos6551_puts
	lda     #<(L010C)
	ldx     #>(L010C)
	jsr     _mos6551_puts
	ldx     #$00
	lda     #$01
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ uptime_service (__near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_uptime_service: near

.segment	"CODE"

	jsr     pushax
	jsr     _uptime
	jsr     pusheax
	lda     #<(_supbuf)
	ldx     #>(_supbuf)
	jsr     pushax
	ldx     #$00
	lda     #$0A
	jsr     _ultoa
	lda     #<(_supbuf)
	ldx     #>(_supbuf)
	jsr     _mos6551_puts
	lda     #<(L0117)
	ldx     #>(L0117)
	jsr     _mos6551_puts
	ldx     #$00
	lda     #$01
	jmp     incsp2

.endproc

